api_platform:
    title: Hello API Platform
    version: 1.0.0
    enable_swagger_ui: true
    enable_re_doc: true
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
